# Generated by Django 5.0.4 on 2024-05-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_portal', '0005_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_delivered_on_time',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
